public: true
type: "docs"
tags:
  - "collection"
  - "policy"
  - "preservation"
  - "mission"
  - "appraisal"
title: "Rockefeller Archive Center Collection Policy"
description: "Policy governing the Rockefeller Archive Center's mission, appraisal and preservation statements, and main collecting areas."
